version: 2.1

command:

jobs:
  build:
    docker:
      image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm lint
      - save cache:
        key: "npm packages"
        paths:
          - src/node_modules

  test:
    docker:
      image: circleci/node:13.8.0
    steps:
      - restore_cache:
        keys:
          - "npm packages"
      - run: npm run test

  analyze:
    docker:
      image: circleci/node:13.8.0
    steps:
      - restore_cache:
        keys:
          - "npm packages"
      - run: npm audit

workflow:
  my_workflow:
    jobs:
      - build
      - test:
        requires: build
      - analyze:
        requires: test
